### ISSUE TITLE
添加 aspectd_impl aop 工程到现有工程会报 FileSystemException

### ISSUE THREAD

**Issue by GvcZhang** [alibaba-flutter/aspectd#83]
大佬，现在遇到一个问题，创建一个 aspectd_impl 工程，放在现有工程的同级目录下，然后运行项目，会报下面的错误，单独运行自己的工程不会有问题，请问这个编译报错如何解决？
已尝试过 `flutter clean`操作来处理这个问题，但是没有作用。

```
Running Gradle task 'assembleDebug'...
Error: Could not resolve the package 'flutter_webview_plugin' in 'package:flutter_webview_plugin/flutter_webview_plugin.dart'.
../flutter_test_autotrack/lib/main.dart:5:8: Error: Not found: 'package:flutter_webview_plugin/flutter_webview_plugin.dart'
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';
       ^
Error: Could not resolve the package 'device_info' in 'package:device_info/device_info.dart'.
Error: Could not resolve the package 'date_format' in 'package:date_format/date_format.dart'.
../flutter_test_autotrack/lib/device_info.dart:3:8: Error: Not found: 'package:device_info/device_info.dart'
import 'package:device_info/device_info.dart';
       ^
../flutter_test_autotrack/lib/im_demo/chat/message_item.dart:1:8: Error: Not found: 'package:date_format/date_format.dart'
import 'package:date_format/date_format.dart';
       ^
../flutter_test_autotrack/lib/device_info.dart:21:44: Error: Type 'AndroidDeviceInfo' not found.
Map<String, dynamic> _readAndroidBuildData(AndroidDeviceInfo build) {
                                           ^^^^^^^^^^^^^^^^^
../flutter_test_autotrack/lib/device_info.dart:42:41: Error: Type 'IosDeviceInfo' not found.
Map<String, dynamic> _readIosDeviceInfo(IosDeviceInfo data) {
                                        ^^^^^^^^^^^^^
../flutter_test_autotrack/lib/main.dart:84:28: Error: The method 'WebviewScaffold' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:flutter_test_autotrack/main.dart' ('../flutter_test_autotrack/lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WebviewScaffold'.
        "/friends": (_) => WebviewScaffold(
                           ^^^^^^^^^^^^^^^
../flutter_test_autotrack/lib/device_info.dart:7:3: Error: 'DeviceInfoPlugin' isn't a type.
  DeviceInfoPlugin deviceInfo = new DeviceInfoPlugin();
  ^^^^^^^^^^^^^^^^
../flutter_test_autotrack/lib/device_info.dart:7:37: Error: Method not found: 'DeviceInfoPlugin'.
  DeviceInfoPlugin deviceInfo = new DeviceInfoPlugin();
                                    ^^^^^^^^^^^^^^^^
../flutter_test_autotrack/lib/device_info.dart:21:44: Error: 'AndroidDeviceInfo' isn't a type.
Map<String, dynamic> _readAndroidBuildData(AndroidDeviceInfo build) {
                                           ^^^^^^^^^^^^^^^^^
../flutter_test_autotrack/lib/device_info.dart:42:41: Error: 'IosDeviceInfo' isn't a type.
Map<String, dynamic> _readIosDeviceInfo(IosDeviceInfo data) {
                                        ^^^^^^^^^^^^^
../flutter_test_autotrack/lib/im_demo/chat/message_item.dart:74:17: Error: The method 'formatDate' isn't defined for the class 'MessageItem'.
 - 'MessageItem' is from 'package:flutter_test_autotrack/im_demo/chat/message_item.dart' ('../flutter_test_autotrack/lib/im_demo/chat/message_item.dart').
Try correcting the name to the name of an existing method, or defining a method named 'formatDate'.
                formatDate(message.time, [HH, ':', nn, ':', 'ss']).toString(),
                ^^^^^^^^^^
../flutter_test_autotrack/lib/im_demo/chat/message_item.dart:74:43: Error: The getter 'HH' isn't defined for the class 'MessageItem'.
 - 'MessageItem' is from 'package:flutter_test_autotrack/im_demo/chat/message_item.dart' ('../flutter_test_autotrack/lib/im_demo/chat/message_item.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HH'.
                formatDate(message.time, [HH, ':', nn, ':', 'ss']).toString(),
                                          ^^
../flutter_test_autotrack/lib/im_demo/chat/message_item.dart:74:52: Error: The getter 'nn' isn't defined for the class 'MessageItem'.
 - 'MessageItem' is from 'package:flutter_test_autotrack/im_demo/chat/message_item.dart' ('../flutter_test_autotrack/lib/im_demo/chat/message_item.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'nn'.
                formatDate(message.time, [HH, ':', nn, ':', 'ss']).toString(),
                                                   ^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_webview_plugin%2Fflutter_webview_plugin.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:657:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:825:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:572:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (file:///Users/zhangwei/Documents/work/flutter_workspace/aspectd/lib/src/flutter_frontend_server/server.dart:52:22)
#5      starter (file:///Users/zhangwei/Documents/work/flutter_workspace/aspectd/lib/src/flutter_frontend_server/server.dart:191:27)
#6      main (file:///Users/zhangwei/Documents/work/flutter_workspace/aspectd/lib/src/flutter_frontend_server/starter.dart:13:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


```

**Comment by GvcZhang** [comment]
通过使用这个 issue 中的操作，解决了：https://github.com/alibaba-flutter/aspectd/issues/55
